name: JEE CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [  master, main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 1.8
      - name: build with Gradle
        run:  ./gradlew build
